# Numpy
![]()

## 数组的维度

[>_>]:![](array.png)
<img src="array.png" width="50%">

## 为什么Numpy快？
内存寄存数短  
不需要类型检查  
连续内存存储  

## Application
计算  
绘图  
存储信息
帮助ML

In [6]:
import numpy as npB

## The Basics 

In [36]:
a = np.array([1,2,3],dtype = 'int16')
a

array([1, 2, 3], dtype=int16)

In [30]:
b = np.array([[9.,8.,7.],[6,5,4]]) #两行三列
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [18]:
# Get Dimension 维度
a.ndim

1

In [23]:
# Get shape
print(a.shape,b.shape)

(3,) (2, 3)


In [37]:
# Get Type 内存,默认四字节
a.dtype 

dtype('int16')

In [41]:
# Get Size 字节
a.itemsize # 2
b.itemsize

8

In [40]:
# Get totol size
#a.size * a.itemsize
a.nbytes

6

## Accessing/Changing specific elements,rows,columns,etc

In [67]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [68]:
#a[1,1]
a[1,-6]

9

In [70]:
# 索引
print(a[1,:])
print(a[1,2:-1:2]) #开始，结束(不包括)，步长
a[1,2:-1:1]

[ 8  9 10 11 12 13 14]
[10 12]


array([10, 11, 12, 13])

In [79]:
# 改值
a[0,5] = 20
a[:,1] = 5
a[:,2] = [80,90]
a

array([[ 1,  5, 80,  4,  5, 20,  7],
       [ 8,  5, 90, 11, 12, 13, 14]])