# Numpy
![]()

## 数组的维度

[>_>]:![](array.png)
<img src="array.png" width="70%">

## 为什么Numpy快？
内存寄存数短  
不需要类型检查  
连续内存存储  

## Application
计算  
绘图  
存储信息
帮助ML

In [27]:
import numpy as np

## The Basics 

In [28]:
a = np.array([1,2,3],dtype = 'int16')
a

array([1, 2, 3], dtype=int16)

In [52]:
b = np.array([[9.,8.,7.],[6,5,4]]) #两行三列
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [18]:
# Get Dimension 维度
a.ndim

1

In [23]:
# Get shape
print(a.shape,b.shape)

(3,) (2, 3)


In [37]:
# Get Type 内存,默认四字节
a.dtype 

dtype('int16')

In [41]:
# Get Size 字节
a.itemsize # 2
b.itemsize

8

In [40]:
# Get totol size
#a.size * a.itemsize
a.nbytes

6

## Accessing/Changing specific elements,rows,columns,etc

In [67]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [68]:
#a[1,1]
a[1,-6]

9

In [70]:
# 索引
print(a[1,:])
print(a[1,2:-1:2]) #开始，结束(不包括)，步长
a[1,2:-1:1]

[ 8  9 10 11 12 13 14]
[10 12]


array([10, 11, 12, 13])

In [79]:
# 改值
a[0,5] = 20
a[:,1] = 5
a[:,2] = [80,90]
a

array([[ 1,  5, 80,  4,  5, 20,  7],
       [ 8,  5, 90, 11, 12, 13, 14]])

**3-d example**

In [50]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
#   Get specific element 
b[0,1,1]

4

In [13]:
# replace
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Initializing Different Types of Arrays

In [14]:
# All zeros matrix
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
# All 1s matrix
np.ones((2,3,4), dtype='int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [20]:
# All any other number
np.full((2,3), 88)

array([[88, 88, 88],
       [88, 88, 88]])

In [53]:
# Any other number (full_like)
b 
print(b)
b=np.full_like(b,4)
b

[[9. 8. 7.]
 [6. 5. 4.]]


array([[4., 4., 4.],
       [4., 4., 4.]])

In [66]:
# Random decimal numbers十进制
np.random.rand(2,3)
#np.random.random_sample(b.shape)

array([[0.81596716, 0.81360943, 0.27287417],
       [0.98362798, 0.02158038, 0.34762374]])

In [71]:
# Random Integer values
#number:4 to 7,but not include 7
np.random.randint(4,7, size=(2,3)) 

array([[4, 5, 7],
       [6, 7, 5]])

In [74]:
# The identity matrix 单位矩阵
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [87]:
# Repeat an array
a = np.array([[1,2,3],[4,5,6]])
r1 = a.repeat(3,axis=1)
print(r1)
r2 = a.repeat(3,axis=0)
print(r2)

[[1 1 1 2 2 2 3 3 3]
 [4 4 4 5 5 5 6 6 6]]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [115]:
# the meaning of axis 
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
r0 = a.repeat(3, axis=0)
r1 = a.repeat(3,axis=1)
r2 = a.repeat(3,axis=2)
print("r0=\n",r0)
print("r1=\n",r1)
print("r2=\n",r2)

r0=
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 7  8  9]
  [10 11 12]]

 [[ 7  8  9]
  [10 11 12]]]
r1=
 [[[ 1  2  3]
  [ 1  2  3]
  [ 1  2  3]
  [ 4  5  6]
  [ 4  5  6]
  [ 4  5  6]]

 [[ 7  8  9]
  [ 7  8  9]
  [ 7  8  9]
  [10 11 12]
  [10 11 12]
  [10 11 12]]]
r2=
 [[[ 1  1  1  2  2  2  3  3  3]
  [ 4  4  4  5  5  5  6  6  6]]

 [[ 7  7  7  8  8  8  9  9  9]
  [10 10 10 11 11 11 12 12 12]]]


In [97]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


###  Be careful when copying arrays!!!

In [118]:
a = np.array([1,2,3])
# if you want b related to a
b = a
# if you just want to give a'value to b
b = a.copy()

##  Mathematics

In [127]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [128]:
a + 2

array([3, 4, 5])

In [129]:
a ** 2

array([1, 4, 9], dtype=int32)

In [130]:
a + b

array([5, 7, 9])

In [131]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

##  Linear Algebra

In [135]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

# a * b is fault
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [139]:
# Determinant行列式
c = np.identity(3)
np.linalg.det(c)

1.0

###  Statistic

In [141]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [142]:
np.min(stats)

1

In [146]:
np.max(stats, axis=0)

array([4, 5, 6])

In [147]:
np.max(stats, axis=1)

array([3, 6])

In [148]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [149]:
np.sum(stats,axis=1)

array([ 6, 15])